const products =[{name:'Desktops', titleLink:'DeskTops', productList:[
    {name:'Apple iMac 2018', imgname:'desktop.jpg', id:'2018iMac', linkto:'appleDesktop'},
    {name:'Microsoft Surface Desktop', imgname:'laptop.jpg', id:'surfaceDesktop', linkto:'surfacedesktop'},
    {name:'Dell Lattitude Desktop', imgname:'tablet.jpg', id:'DellDesk', linkto:'delldesk'},
    {name:'HP Pavillon Desktop', imgname:'phone.jpg', id:'HP pavillon', linkto:'hp desktop'},
    {name:'Toshiba Desktop', imgname:'OS74370.jpg', id:'Toshiba', linkto:'televisions'},
    {name:'Samsung Desktop', imgname:'airconditioner.jpg', id:'Air Conditioners', linkto:'airconditioners'},
    {name:'Asus Desktop', imgname:'flash.jpg', id:'Storge Devices', linkto:'Devices'},
    {name:'Lenovo Desktop', imgname:'keyboard.jpg', id:'Keyboards And Mouse', linkto:'Mouse'},
]},
{name:'Laptops', titleLink:'LapTops', productList:[
    {name:'VivoBook', imgname:'desktop.jpg', id:'VivoBook', linkto:'vivobook'},
    {name:'MiBook', imgname:'laptop.jpg', id:'MiBook', linkto:'mibook'},
    {name:'RedmiBook', imgname:'tablet.jpg', id:'RedmiBook', linkto:'RedmiBook'},
    {name:'MacBook', imgname:'phone.jpg', id:'MacBook', linkto:'MacBook'},
    {name:'Surface Book', imgname:'OS74370.jpg', id:'Surface Book', linkto:'SurfaceBook'},
    {name:'Alienware', imgname:'airconditioner.jpg', id:'Alienware', linkto:'alienware'},
    {name:'Dell Lattitude', imgname:'flash.jpg', id:'Dell Lattitude', linkto:'delllatitude'},
]},
{name:'Tablets', titleLink:'Tablets', productList:[
    {name:'iPad', imgname:'desktop.jpg', id:'iPad', linkto:'ipad'},
    {name:'MiPad', imgname:'laptop.jpg', id:'MiPad', linkto:'MiPad'},
    {name:'Galaxy Tab', imgname:'tablet.jpg', id:'GalaxyTab', linkto:'GalaxyTab'},
    {name:'Mate Pad', imgname:'phone.jpg', id:'MatePad', linkto:'MatePad'},
]},
{name:'Phones', titleLink:'Phones', productList:[
    {name:'iPhone', imgname:'desktop.jpg', id:'iPhone', linkto:'iPhone'},
    {name:'Samsung', imgname:'laptop.jpg', id:'Samsung', linkto:'Samsungphone'},
    {name:'Huawei', imgname:'tablet.jpg', id:'Huawei', linkto:'Huaweiphone'},
    {name:'Infinix', imgname:'phone.jpg', id:'Infinix', linkto:'Infinixphone'},
    {name:'Xiaomi', imgname:'OS74370.jpg', id:'Xiaomi', linkto:'Xiaomphonei'},
    {name:'Tecno', imgname:'airconditioner.jpg', id:'Tecno', linkto:'tecnophone'},
    {name:'Oppo', imgname:'flash.jpg', id:'Oppo', linkto:'Oppophone'},
    {name:'iTel', imgname:'keyboard.jpg', id:'iTel', linkto:'itelphone'},
]},
{name:'Television', titleLink:'tv', productList:[
    {name:'Samsung', imgname:'desktop.jpg', id:'Samsung', linkto:'Samsungtv'},
    {name:'Infinix', imgname:'laptop.jpg', id:'Infinix', linkto:'Infinixtv'},
    {name:'LG', imgname:'tablet.jpg', id:'LG', linkto:'LGtv'},
    {name:'Sony', imgname:'phone.jpg', id:'Sony', linkto:'Sonytv'},
    {name:'Xiaomi', imgname:'OS74370.jpg', id:'Xiaomi', linkto:'Xiaomitv'},
    {name:'Huawei', imgname:'airconditioner.jpg', id:'Huawei', linkto:'huaweitv'},
]},
]
export default products